
# ROS 2 Humble + Gazebo Harmonic

FROM ros:humble

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ENV ROS_WS=/opt/ros_ws

# Locale and base tools
RUN apt-get update && apt-get install -y \
    locales \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common \
    build-essential \
    cmake \
    git \
    wget \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Gazebo Harmonic repository

RUN curl -sSL https://packages.osrfoundation.org/gazebo.key \
    | gpg --dearmor -o /usr/share/keyrings/gazebo-archive-keyring.gpg

RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/gazebo-archive-keyring.gpg] \
    http://packages.osrfoundation.org/gazebo/ubuntu-stable \
    $(lsb_release -cs) main" \
    > /etc/apt/sources.list.d/gazebo-stable.list


# Install ROS + Gazebo + dependencies

RUN apt-get update && apt-get install -y \
    ros-humble-xacro \
    ros-humble-simple-launch \
    ros-humble-slider-publisher \
    ros-humble-ros-gz-bridge \
    ros-humble-ros-gz-sim \
    gz-harmonic \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    mesa-utils \
    && rm -rf /var/lib/apt/lists/*


# rosdep

RUN rosdep init || true && rosdep update

# Workspace

RUN mkdir -p ${ROS_WS}/src
WORKDIR ${ROS_WS}

# Clone source dependencies

RUN cd src && \
    git clone https://github.com/CentraleNantesROV/auv_control.git && \
    git clone https://github.com/oKermorgant/pose_to_tf.git && \
    git clone https://github.com/oKermorgant/bluerov2_description.git

# Install package dependencies

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    rosdep install --from-paths src --ignore-src -r -y

# Build

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --symlink-install

# DDS / Networking configuration

ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# Optional: force discovery on LAN
ENV FASTRTPS_DEFAULT_PROFILES_FILE=/opt/fastdds.xml

# Environment setup

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc && \
    echo "source ${ROS_WS}/install/setup.bash" >> /root/.bashrc

CMD ["bash"]
